server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/quickeats_restaurant
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000 # Cache TTL 10 minutes (in milliseconds)
      cache-null-values: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
