version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: quickeats-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quickeats_user
    volumes:
      - ./docker/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quickeats-network

  mongodb:
    image: mongo:7.0
    container_name: quickeats-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: quickeats_restaurant
    volumes:
      - mongodb_data:/data/db
    networks:
      - quickeats-network

  redis:
    image: redis:7.2-alpine
    container_name: quickeats-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - quickeats-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: quickeats-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REREPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - quickeats-network

  zipkin:
    image: openzipkin/zipkin
    container_name: quickeats-zipkin
    ports:
      - "9411:9411"
    networks:
      - quickeats-network

  prometheus:
    image: prom/prometheus:latest
    container_name: quickeats-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - quickeats-network

  grafana:
    image: grafana/grafana:latest
    container_name: quickeats-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - quickeats-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  quickeats-network:
    driver: bridge
